FROM python:3.11-slim

# -----------------------------------
# PYTHON SETTINGS
# -----------------------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# -----------------------------------
# WORKING DIRECTORY
# -----------------------------------
WORKDIR /frontend

# -----------------------------------
# SYSTEM DEPENDENCIES
# -----------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# -----------------------------------
# COPY REQUIREMENTS
# -----------------------------------
COPY requirements.txt .

# -----------------------------------
# INSTALL DEPENDENCIES
# -----------------------------------
RUN pip install --no-cache-dir -r requirements.txt

# -----------------------------------
# COPY PROJECT FILES
# -----------------------------------
COPY . .

# -----------------------------------
# STREAMLIT SETTINGS
# -----------------------------------
ENV STREAMLIT_SERVER_HEADLESS=true

# -----------------------------------
# EXPOSE PORT
# -----------------------------------
EXPOSE 8501

# -----------------------------------
# START STREAMLIT
# -----------------------------------
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]